package com.planjoy.r7
import android.app.*
import android.app.job.*
import android.appwidget.*
import android.content.*
import android.widget.RemoteViews
import java.time.*
object BackgroundScheduler{fun schedule(c:Context){c.getSystemService(JobScheduler::class.java).schedule(JobInfo.Builder(7007,ComponentName(c,SyncJobService::class.java)).setRequiredNetworkType(JobInfo.NETWORK_TYPE_ANY).setPersisted(true).setPeriodic(15*60*1000L).build())}}
class SyncJobService:JobService(){override fun onStartJob(p:JobParameters?):Boolean{Thread{val r=SyncEngine.sync(this);jobFinished(p,!r.ok)}.start();return true};override fun onStopJob(p:JobParameters?)=true}
class BootReceiver:BroadcastReceiver(){override fun onReceive(c:Context,i:Intent){if(i.action!=Intent.ACTION_BOOT_COMPLETED)return;BackgroundScheduler.schedule(c);ReminderScheduler.schedule(c)}}
object ReminderScheduler{fun schedule(c:Context){val n=System.currentTimeMillis()/1000;val t=PlanJoyDb.get(c).rows("task").mapNotNull{Codec.task(it.id,it.payload)}.filter{!it.completed&&it.startUtc>n}.minByOrNull{it.startUtc}?:return;val at=(t.startUtc-(if(t.reminderLead>=0)t.reminderLead*60 else 0))*1000;val p=PendingIntent.getBroadcast(c,t.id.hashCode(),Intent(c,ReminderReceiver::class.java).putExtra("id",t.id).putExtra("title",t.title),PendingIntent.FLAG_UPDATE_CURRENT or PendingIntent.FLAG_IMMUTABLE);c.getSystemService(AlarmManager::class.java).setAndAllowWhileIdle(AlarmManager.RTC_WAKEUP,at,p)}}
class ReminderReceiver:BroadcastReceiver(){override fun onReceive(c:Context,i:Intent){val m=c.getSystemService(NotificationManager::class.java);m.createNotificationChannel(NotificationChannel("planjoy","PlanJoy reminders",NotificationManager.IMPORTANCE_HIGH));val id=i.getStringExtra("id")?:"";val op=PendingIntent.getActivity(c,id.hashCode(),Intent(c,MainActivity::class.java).putExtra("task_id",id),PendingIntent.FLAG_UPDATE_CURRENT or PendingIntent.FLAG_IMMUTABLE);val b=Notification.Builder(c,"planjoy");m.notify(id.hashCode(),b.setSmallIcon(android.R.drawable.ic_dialog_info).setContentTitle(i.getStringExtra("title")?:"PlanJoy").setContentText("PlanJoy").setContentIntent(op).setAutoCancel(true).build());ReminderScheduler.schedule(c)}}
class TodayWidget:AppWidgetProvider(){override fun onUpdate(c:Context,m:AppWidgetManager,ids:IntArray){ids.forEach{update(c,m,it)}};companion object{fun update(c:Context,m:AppWidgetManager,id:Int){val fa=PlanJoyDb.get(c).setting("lang","en")=="fa";val x=PlanJoyDb.get(c).rows("task").mapNotNull{Codec.task(it.id,it.payload)}.filter{!it.completed}.take(4);val r=RemoteViews(c.packageName,R.layout.widget_today);r.setTextViewText(R.id.widget_title,if(fa)"PlanJoy • امروز" else "PlanJoy • Today");r.setTextViewText(R.id.widget_tasks,if(x.isEmpty())if(fa)"کاری باقی نمانده" else "No remaining tasks" else x.joinToString("\n"){"• ${it.title}"});r.setOnClickPendingIntent(R.id.widget_tasks,PendingIntent.getActivity(c,0,Intent(c,MainActivity::class.java),PendingIntent.FLAG_IMMUTABLE));m.updateAppWidget(id,r)}}}
