package com.planjoy.r7
import android.app.*
import android.app.job.*
import android.appwidget.*
import android.content.*
import android.widget.RemoteViews
import java.time.*

object BackgroundScheduler{
    fun schedule(c:Context){runCatching{c.getSystemService(JobScheduler::class.java).schedule(JobInfo.Builder(7007,ComponentName(c,SyncJobService::class.java)).setRequiredNetworkType(JobInfo.NETWORK_TYPE_ANY).setPersisted(true).setPeriodic(15*60*1000L).build())}}
}
class SyncJobService:JobService(){override fun onStartJob(p:JobParameters?):Boolean{Thread{val r=SyncEngine.sync(this);jobFinished(p,!r.ok)}.start();return true};override fun onStopJob(p:JobParameters?)=true}
class BootReceiver:BroadcastReceiver(){override fun onReceive(c:Context,i:Intent){if(i.action!=Intent.ACTION_BOOT_COMPLETED)return;BackgroundScheduler.schedule(c);ReminderScheduler.schedule(c);R72WidgetUpdater.refreshAll(c)}}

object ReminderScheduler{
    private fun alarm(c:Context)=c.getSystemService(AlarmManager::class.java)
    private fun pi(c:Context,t:TaskModel,request:Int,action:String="REMIND")=PendingIntent.getBroadcast(c,request,Intent(c,ReminderReceiver::class.java).setAction(action).putExtra("id",t.id).putExtra("title",t.title),PendingIntent.FLAG_UPDATE_CURRENT or PendingIntent.FLAG_IMMUTABLE)
    fun schedule(c:Context){
        val n=System.currentTimeMillis()/1000;val db=PlanJoyDb.get(c);val tasks=R72Store.orderedTasks(db).filter{!it.completed&&it.startUtc>0}.sortedBy{it.startUtc}.take(64)
        tasks.forEachIndexed{idx,t->val atSec=(t.startUtc-(if(t.reminderLead>=0)t.reminderLead*60 else 0));if(t.reminderLead>=0&&atSec>n)runCatching{alarm(c).setAndAllowWhileIdle(AlarmManager.RTC_WAKEUP,atSec*1000,pi(c,t,(t.id+":base").hashCode()))}}
    }
    fun snooze(c:Context,t:TaskModel,minutes:Int){val at=System.currentTimeMillis()+minutes.coerceAtLeast(1)*60_000L;runCatching{alarm(c).setAndAllowWhileIdle(AlarmManager.RTC_WAKEUP,at,pi(c,t,(t.id+":snooze:"+minutes+":"+(at/60000)).hashCode(),"SNOOZED"))}}
}
class ReminderReceiver:BroadcastReceiver(){
    override fun onReceive(c:Context,i:Intent){
        val db=PlanJoyDb.get(c);val id=i.getStringExtra("id")?:return;val t=db.rows("task").mapNotNull{Codec.task(it.id,it.payload)}.firstOrNull{it.id==id}?:return;if(t.completed)return
        val fa=db.setting("lang","en")=="fa";val m=c.getSystemService(NotificationManager::class.java);m.createNotificationChannel(NotificationChannel("planjoy_plans",if(fa)"یادآوری برنامه‌ها" else "Plan reminders",NotificationManager.IMPORTANCE_HIGH).apply{description=if(fa)"یادآوری، تعویق و تکمیل سریع برنامه‌ها" else "Plan reminders with snooze and completion actions"})
        val open=PendingIntent.getActivity(c,(id+"open").hashCode(),Intent(c,MainActivity::class.java).putExtra("task_id",id),PendingIntent.FLAG_UPDATE_CURRENT or PendingIntent.FLAG_IMMUTABLE)
        fun action(a:String,min:Int=0)=PendingIntent.getBroadcast(c,(id+a+min).hashCode(),Intent(c,ReminderActionReceiver::class.java).setAction(a).putExtra("id",id).putExtra("min",min),PendingIntent.FLAG_UPDATE_CURRENT or PendingIntent.FLAG_IMMUTABLE)
        val b=Notification.Builder(c,"planjoy_plans").setSmallIcon(android.R.drawable.ic_dialog_info).setContentTitle(t.title).setContentText(if(fa)"یک قدم کوچیک؛ انجامش بده یا کمی عقبش بنداز." else "A small nudge — finish it or give yourself a little more time.").setContentIntent(open).setAutoCancel(true).setCategory(Notification.CATEGORY_REMINDER).addAction(android.R.drawable.ic_menu_agenda,if(fa)"انجام شد" else "Done",action("COMPLETE")).addAction(android.R.drawable.ic_popup_sync,if(fa)"۱۰ دقیقه بعد" else "10 min",action("SNOOZE",10)).addAction(android.R.drawable.ic_popup_sync,if(fa)"۳۰ دقیقه بعد" else "30 min",action("SNOOZE",30))
        m.notify(id.hashCode(),b.build());db.noteNotification(id,"fired");val continuous=R72Store.taskMeta(db,id).continuousMinutes;if(continuous>0)ReminderScheduler.snooze(c,t,continuous);ReminderScheduler.schedule(c)
    }
}
class ReminderActionReceiver:BroadcastReceiver(){
    override fun onReceive(c:Context,i:Intent){val db=PlanJoyDb.get(c);val id=i.getStringExtra("id")?:return;val t=db.rows("task").mapNotNull{Codec.task(it.id,it.payload)}.firstOrNull{it.id==id}?:return;when(i.action){"COMPLETE"->{if(!t.completed){val done=t.copy(completed=true,completedUtc=System.currentTimeMillis()/1000);db.save("task",id,Codec.task(done));db.saveReward("task:$id","task","task",id,10,1,done.completedUtc);R72Recurrence.advanceOnComplete(c,done);SoundFx.play(c,1)};db.noteNotification(id,"complete");c.getSystemService(NotificationManager::class.java).cancel(id.hashCode());R72WidgetUpdater.refreshAll(c)};"SNOOZE"->{db.noteNotification(id,"snooze",true);ReminderScheduler.snooze(c,t,i.getIntExtra("min",10))}}}
}

private fun widgetBg(c:Context):Int=when(PlanJoyDb.get(c).setting("widget_theme","0").toIntOrNull()){1->0xFFF0F6F3.toInt();2->0xFFFFEEF2.toInt();3->0xFF2D2A38.toInt();else->0xFFFFF7F0.toInt()}
private fun widgetText(c:Context):Int=if(PlanJoyDb.get(c).setting("widget_theme","0")=="3")0xFFF8F5FA.toInt() else 0xFF2B2D31.toInt()

class TodayWidget:AppWidgetProvider(){override fun onUpdate(c:Context,m:AppWidgetManager,ids:IntArray){ids.forEach{update(c,m,it)}};companion object{fun update(c:Context,m:AppWidgetManager,id:Int){val db=PlanJoyDb.get(c);val fa=db.setting("lang","en")=="fa";val privacy=db.setting("widget_privacy","0")=="1";val count=db.setting("widget_today_count","4").toIntOrNull()?.coerceIn(2,8)?:4;val x=R72Store.orderedTasks(db).filter{!it.completed&&it.parentId.isBlank()}.take(count);val r=RemoteViews(c.packageName,if(fa)R.layout.widget_today_fa else R.layout.widget_today);r.setInt(R.id.widget_root,"setBackgroundColor",widgetBg(c));r.setTextColor(R.id.widget_title,widgetText(c));r.setTextColor(R.id.widget_tasks,widgetText(c));r.setTextViewText(R.id.widget_title,if(fa)"پلن‌جوی • امروز" else "PlanJoy • Today");r.setTextViewText(R.id.widget_tasks,if(privacy)if(fa)"جزئیات برای حریم خصوصی مخفی است" else "Details hidden for privacy" else if(x.isEmpty())if(fa)"همه‌چیز مرتب است؛ برنامه‌ای منتظر نیست." else "All clear — no plans are waiting." else x.joinToString("\n"){"• ${it.title}"});r.setOnClickPendingIntent(R.id.widget_tasks,PendingIntent.getActivity(c,0,Intent(c,MainActivity::class.java),PendingIntent.FLAG_IMMUTABLE));m.updateAppWidget(id,r)}}}
class FocusWidget:AppWidgetProvider(){override fun onUpdate(c:Context,m:AppWidgetManager,ids:IntArray){ids.forEach{update(c,m,it)}};companion object{fun update(c:Context,m:AppWidgetManager,id:Int){val db=PlanJoyDb.get(c);val fa=db.setting("lang","en")=="fa";val days=db.setting("widget_focus_days","7").toIntOrNull()?.coerceIn(1,30)?:7;val min=db.rows("focus").mapNotNull{Codec.focus(it.id,it.payload)}.filter{it.endedUtc>System.currentTimeMillis()/1000-days*86400L}.sumOf{it.actualSeconds}/60;val r=RemoteViews(c.packageName,R.layout.widget_focus);r.setInt(R.id.widget_focus_root,"setBackgroundColor",widgetBg(c));r.setTextColor(R.id.widget_focus_title,widgetText(c));r.setTextColor(R.id.widget_focus_value,widgetText(c));r.setTextViewText(R.id.widget_focus_title,if(fa)"پلن‌جوی • تمرکز" else "PlanJoy • Focus");r.setTextViewText(R.id.widget_focus_value,if(db.setting("widget_privacy","0")=="1")"•••" else if(fa)"${Jalali.faDigits(min.toString())} دقیقه" else "$min min");r.setTextViewText(R.id.widget_focus_hint,if(fa)"در ${Jalali.faDigits(days.toString())} روز گذشته" else "last $days days");r.setOnClickPendingIntent(R.id.widget_focus_value,PendingIntent.getActivity(c,1,Intent(c,MainActivity::class.java).putExtra("open","focus"),PendingIntent.FLAG_UPDATE_CURRENT or PendingIntent.FLAG_IMMUTABLE));m.updateAppWidget(id,r)}}}
class GoalWidget:AppWidgetProvider(){override fun onUpdate(c:Context,m:AppWidgetManager,ids:IntArray){ids.forEach{update(c,m,it)}};companion object{fun update(c:Context,m:AppWidgetManager,id:Int){val db=PlanJoyDb.get(c);val fa=db.setting("lang","en")=="fa";val g=db.rows("goal").mapNotNull{Codec.goal(it.id,it.payload)}.firstOrNull{it.status==0};val privacy=db.setting("widget_privacy","0")=="1";val r=RemoteViews(c.packageName,R.layout.widget_goal);r.setInt(R.id.widget_goal_root,"setBackgroundColor",widgetBg(c));r.setTextColor(R.id.widget_goal_title,widgetText(c));r.setTextColor(R.id.widget_goal_name,widgetText(c));r.setTextViewText(R.id.widget_goal_title,if(fa)"پلن‌جوی • هدف" else "PlanJoy • Goal");r.setTextViewText(R.id.widget_goal_name,if(privacy)if(fa)"هدف خصوصی" else "Private goal" else g?.title?:if(fa)"هنوز هدف فعالی نداری" else "No active goal yet");r.setTextViewText(R.id.widget_goal_progress,if(g==null)"—" else if(fa)"${Jalali.faDigits(g.progress.toString())}٪" else "${g.progress}%");r.setOnClickPendingIntent(R.id.widget_goal_name,PendingIntent.getActivity(c,2,Intent(c,MainActivity::class.java).putExtra("open","goals"),PendingIntent.FLAG_UPDATE_CURRENT or PendingIntent.FLAG_IMMUTABLE));m.updateAppWidget(id,r)}}}
class CountdownWidget:AppWidgetProvider(){override fun onUpdate(c:Context,m:AppWidgetManager,ids:IntArray){ids.forEach{update(c,m,it)}};companion object{fun update(c:Context,m:AppWidgetManager,id:Int){val db=PlanJoyDb.get(c);val fa=db.setting("lang","en")=="fa";val x=db.rows("countdown").mapNotNull{Codec.countdown(it.id,it.payload)}.filter{it.targetUtc>System.currentTimeMillis()/1000}.minByOrNull{it.targetUtc};val days=x?.let{((it.targetUtc-System.currentTimeMillis()/1000)/86400).coerceAtLeast(0)};val r=RemoteViews(c.packageName,R.layout.widget_countdown);r.setInt(R.id.widget_countdown_root,"setBackgroundColor",widgetBg(c));r.setTextColor(R.id.widget_countdown_title,widgetText(c));r.setTextColor(R.id.widget_countdown_value,widgetText(c));r.setTextViewText(R.id.widget_countdown_title,if(fa)"پلن‌جوی • شمارش‌معکوس" else "PlanJoy • Countdown");r.setTextViewText(R.id.widget_countdown_name,if(db.setting("widget_privacy","0")=="1")if(fa)"رویداد خصوصی" else "Private event" else x?.title?:if(fa)"شمارش‌معکوسی نیست" else "No countdown");r.setTextViewText(R.id.widget_countdown_value,days?.let{if(fa)"${Jalali.faDigits(it.toString())} روز" else "$it days"}?:"—");r.setOnClickPendingIntent(R.id.widget_countdown_name,PendingIntent.getActivity(c,3,Intent(c,MainActivity::class.java).putExtra("open","countdown"),PendingIntent.FLAG_UPDATE_CURRENT or PendingIntent.FLAG_IMMUTABLE));m.updateAppWidget(id,r)}}}
