package com.planjoy.r7
import android.content.*
import android.database.sqlite.*
import java.util.UUID
class PlanJoyDb private constructor(ctx:Context):SQLiteOpenHelper(ctx,"planjoy_r7.db",null,9){
 companion object{@Volatile private var I:PlanJoyDb?=null;fun get(c:Context)=I?:synchronized(this){I?:PlanJoyDb(c.applicationContext).also{I=it}}}
 override fun onCreate(d:SQLiteDatabase){d.execSQL("CREATE TABLE entity(type TEXT,id TEXT,payload TEXT NOT NULL DEFAULT '',tombstone INTEGER NOT NULL DEFAULT 0,revision INTEGER NOT NULL DEFAULT 0,hlc_utc INTEGER NOT NULL DEFAULT 0,hlc_counter INTEGER NOT NULL DEFAULT 0,device_id TEXT NOT NULL DEFAULT '',updated_utc INTEGER NOT NULL DEFAULT 0,PRIMARY KEY(type,id))");d.execSQL("CREATE INDEX idx_entity_type_live ON entity(type,tombstone,updated_utc DESC)");d.execSQL("CREATE TABLE journal(local_seq INTEGER PRIMARY KEY AUTOINCREMENT,op_id TEXT UNIQUE NOT NULL,type TEXT NOT NULL,entity_id TEXT NOT NULL,kind INTEGER NOT NULL,revision INTEGER NOT NULL,hlc_utc INTEGER NOT NULL,hlc_counter INTEGER NOT NULL,payload TEXT NOT NULL DEFAULT '',state INTEGER NOT NULL DEFAULT 0)");d.execSQL("CREATE TABLE runtime(singleton INTEGER PRIMARY KEY CHECK(singleton=1),device_id TEXT NOT NULL,last_hlc_utc INTEGER NOT NULL DEFAULT 0,last_hlc_counter INTEGER NOT NULL DEFAULT 0,server_cursor INTEGER NOT NULL DEFAULT 0,last_sync_utc INTEGER NOT NULL DEFAULT 0)");d.execSQL("INSERT INTO runtime VALUES(1,'${UUID.randomUUID()}',0,0,0,0)");d.execSQL("CREATE TABLE settings(k TEXT PRIMARY KEY,v TEXT NOT NULL)");d.execSQL("CREATE TABLE notification_state(task_id TEXT PRIMARY KEY,last_fired_utc INTEGER NOT NULL DEFAULT 0,last_action TEXT NOT NULL DEFAULT '',snooze_count INTEGER NOT NULL DEFAULT 0)");d.execSQL("CREATE TABLE sync_conflict(id TEXT PRIMARY KEY,type TEXT NOT NULL,entity_id TEXT NOT NULL,local_payload TEXT NOT NULL DEFAULT '',remote_payload TEXT NOT NULL DEFAULT '',local_revision INTEGER NOT NULL DEFAULT 0,remote_revision INTEGER NOT NULL DEFAULT 0,winner INTEGER NOT NULL DEFAULT 0,created_utc INTEGER NOT NULL DEFAULT 0,resolved_utc INTEGER NOT NULL DEFAULT 0,resolution TEXT NOT NULL DEFAULT '')");d.execSQL("CREATE INDEX idx_sync_conflict_open ON sync_conflict(resolved_utc,created_utc DESC)");d.execSQL("CREATE TABLE diagnostic_event(id INTEGER PRIMARY KEY AUTOINCREMENT,kind TEXT NOT NULL,message TEXT NOT NULL DEFAULT '',created_utc INTEGER NOT NULL DEFAULT 0)")}
 override fun onUpgrade(d:SQLiteDatabase,o:Int,n:Int){if(o<8){d.execSQL("CREATE INDEX IF NOT EXISTS idx_entity_type_live ON entity(type,tombstone,updated_utc DESC)");d.execSQL("CREATE TABLE IF NOT EXISTS notification_state(task_id TEXT PRIMARY KEY,last_fired_utc INTEGER NOT NULL DEFAULT 0,last_action TEXT NOT NULL DEFAULT '',snooze_count INTEGER NOT NULL DEFAULT 0)")};if(o<9){d.execSQL("CREATE TABLE IF NOT EXISTS sync_conflict(id TEXT PRIMARY KEY,type TEXT NOT NULL,entity_id TEXT NOT NULL,local_payload TEXT NOT NULL DEFAULT '',remote_payload TEXT NOT NULL DEFAULT '',local_revision INTEGER NOT NULL DEFAULT 0,remote_revision INTEGER NOT NULL DEFAULT 0,winner INTEGER NOT NULL DEFAULT 0,created_utc INTEGER NOT NULL DEFAULT 0,resolved_utc INTEGER NOT NULL DEFAULT 0,resolution TEXT NOT NULL DEFAULT '')");d.execSQL("CREATE INDEX IF NOT EXISTS idx_sync_conflict_open ON sync_conflict(resolved_utc,created_utc DESC)");d.execSQL("CREATE TABLE IF NOT EXISTS diagnostic_event(id INTEGER PRIMARY KEY AUTOINCREMENT,kind TEXT NOT NULL,message TEXT NOT NULL DEFAULT '',created_utc INTEGER NOT NULL DEFAULT 0)")}}
 @Synchronized fun setting(k:String,def:String="")=readableDatabase.rawQuery("SELECT v FROM settings WHERE k=?",arrayOf(k)).use{if(it.moveToFirst())it.getString(0) else def}
 @Synchronized fun setSetting(k:String,v:String){writableDatabase.execSQL("INSERT INTO settings(k,v) VALUES(?,?) ON CONFLICT(k) DO UPDATE SET v=excluded.v",arrayOf(k,v))}
 @Synchronized fun deviceId()=readableDatabase.rawQuery("SELECT device_id FROM runtime WHERE singleton=1",null).use{it.moveToFirst();it.getString(0)}
 private fun clock(d:SQLiteDatabase):Pair<Long,Long>{val n=System.currentTimeMillis()/1000;var h=0L;var c=0L;d.rawQuery("SELECT last_hlc_utc,last_hlc_counter FROM runtime WHERE singleton=1",null).use{it.moveToFirst();h=it.getLong(0);c=it.getLong(1)};val nh=maxOf(n,h);val nc=if(n>h)0 else c+1;d.execSQL("UPDATE runtime SET last_hlc_utc=?,last_hlc_counter=? WHERE singleton=1",arrayOf(nh,nc));return nh to nc}
 @Synchronized fun save(type:String,id:String,payload:String,del:Boolean=false){val d=writableDatabase;d.beginTransaction();try{var rev=0L;d.rawQuery("SELECT revision FROM entity WHERE type=? AND id=?",arrayOf(type,id)).use{if(it.moveToFirst())rev=it.getLong(0)};rev++;val(h,c)=clock(d);val dev=deviceId();val p=if(del)"" else payload;val cv=ContentValues().apply{put("type",type);put("id",id);put("payload",p);put("tombstone",if(del)1 else 0);put("revision",rev);put("hlc_utc",h);put("hlc_counter",c);put("device_id",dev);put("updated_utc",System.currentTimeMillis()/1000)};d.insertWithOnConflict("entity",null,cv,SQLiteDatabase.CONFLICT_REPLACE);val j=ContentValues().apply{put("op_id","op_"+UUID.randomUUID().toString().replace("-",""));put("type",type);put("entity_id",id);put("kind",if(del)3 else if(rev==1L)1 else 2);put("revision",rev);put("hlc_utc",h);put("hlc_counter",c);put("payload",p)};d.insertOrThrow("journal",null,j);d.setTransactionSuccessful()}finally{d.endTransaction()}}
 @Synchronized fun rows(type:String):List<EntityRow>{val x=mutableListOf<EntityRow>();readableDatabase.rawQuery("SELECT type,id,payload,tombstone,revision,hlc_utc,hlc_counter,device_id FROM entity WHERE type=? AND tombstone=0 ORDER BY updated_utc DESC",arrayOf(type)).use{c->while(c.moveToNext())x+=EntityRow(c.getString(0),c.getString(1),c.getString(2),c.getInt(3)!=0,c.getLong(4),c.getLong(5),c.getLong(6),c.getString(7))};return x}
 @Synchronized fun pending():List<SyncOp>{val x=mutableListOf<SyncOp>();val dev=deviceId();readableDatabase.rawQuery("SELECT op_id,type,entity_id,kind,revision,hlc_utc,hlc_counter,payload FROM journal WHERE state=0 ORDER BY local_seq LIMIT 200",null).use{c->while(c.moveToNext())x+=SyncOp(0,c.getString(0),dev,c.getString(1),c.getString(2),c.getInt(3),c.getLong(4),c.getLong(5),c.getLong(6),c.getString(7))};return x}
 @Synchronized fun ack(ids:List<String>){ids.forEach{writableDatabase.execSQL("UPDATE journal SET state=2 WHERE op_id=?",arrayOf(it))}}
 @Synchronized fun apply(op:SyncOp,plain:String){val d=writableDatabase;var local:EntityRow?=null;d.rawQuery("SELECT type,id,payload,tombstone,revision,hlc_utc,hlc_counter,device_id FROM entity WHERE type=? AND id=?",arrayOf(op.type,op.entityId)).use{c->if(c.moveToFirst())local=EntityRow(c.getString(0),c.getString(1),c.getString(2),c.getInt(3)!=0,c.getLong(4),c.getLong(5),c.getLong(6),c.getString(7))};val pending=d.rawQuery("SELECT COUNT(*) FROM journal WHERE type=? AND entity_id=? AND state=0",arrayOf(op.type,op.entityId)).use{it.moveToFirst();it.getInt(0)>0};val win=local==null||compareValues(op.revision,local!!.revision)>0||(op.revision==local!!.revision&&(op.hlcUtc>local!!.hlcUtc||op.hlcUtc==local!!.hlcUtc&&(op.hlcCounter>local!!.hlcCounter||op.hlcCounter==local!!.hlcCounter&&op.deviceId>=local!!.deviceId)));if(local!=null&&pending&&op.deviceId!=deviceId()&&local!!.payload!=plain){val cid="cf_"+UUID.randomUUID().toString().replace("-","");val cv=ContentValues().apply{put("id",cid);put("type",op.type);put("entity_id",op.entityId);put("local_payload",local!!.payload);put("remote_payload",plain);put("local_revision",local!!.revision);put("remote_revision",op.revision);put("winner",if(win)2 else 1);put("created_utc",System.currentTimeMillis()/1000)};d.insert("sync_conflict",null,cv)};if(win){val cv=ContentValues().apply{put("type",op.type);put("id",op.entityId);put("payload",if(op.kind==3)"" else plain);put("tombstone",if(op.kind==3)1 else 0);put("revision",op.revision);put("hlc_utc",op.hlcUtc);put("hlc_counter",op.hlcCounter);put("device_id",op.deviceId);put("updated_utc",System.currentTimeMillis()/1000)};d.insertWithOnConflict("entity",null,cv,SQLiteDatabase.CONFLICT_REPLACE)}}
 @Synchronized fun conflicts(openOnly:Boolean=true):List<R73Conflict>{val out=mutableListOf<R73Conflict>();val q=if(openOnly)"SELECT id,type,entity_id,local_payload,remote_payload,local_revision,remote_revision,winner,created_utc,resolved_utc,resolution FROM sync_conflict WHERE resolved_utc=0 ORDER BY created_utc DESC" else "SELECT id,type,entity_id,local_payload,remote_payload,local_revision,remote_revision,winner,created_utc,resolved_utc,resolution FROM sync_conflict ORDER BY created_utc DESC LIMIT 100";readableDatabase.rawQuery(q,null).use{c->while(c.moveToNext())out+=R73Conflict(c.getString(0),c.getString(1),c.getString(2),c.getString(3),c.getString(4),c.getLong(5),c.getLong(6),c.getInt(7),c.getLong(8),c.getLong(9),c.getString(10))};return out}
 @Synchronized fun resolveConflict(id:String,choice:String):Boolean{val c=conflicts(false).firstOrNull{it.id==id}?:return false;when(choice){"local"->save(c.type,c.entityId,c.localPayload);"remote"->save(c.type,c.entityId,c.remotePayload);"both"->{save(c.type,c.entityId,c.localPayload);save(c.type,"copy_"+UUID.randomUUID().toString().replace("-",""),c.remotePayload)};else->return false};writableDatabase.execSQL("UPDATE sync_conflict SET resolved_utc=?,resolution=? WHERE id=?",arrayOf(System.currentTimeMillis()/1000,choice,id));return true}
 @Synchronized fun diagnostic(kind:String,msg:String){writableDatabase.execSQL("INSERT INTO diagnostic_event(kind,message,created_utc) VALUES(?,?,?)",arrayOf(kind,msg.take(1500),System.currentTimeMillis()/1000));writableDatabase.execSQL("DELETE FROM diagnostic_event WHERE id NOT IN(SELECT id FROM diagnostic_event ORDER BY id DESC LIMIT 200)")}
 @Synchronized fun notificationStats():Triple<Int,Long,Int>{return readableDatabase.rawQuery("SELECT COUNT(*),COALESCE(MAX(last_fired_utc),0),COALESCE(SUM(snooze_count),0) FROM notification_state",null).use{it.moveToFirst();Triple(it.getInt(0),it.getLong(1),it.getInt(2))}}
 @Synchronized fun noteNotification(taskId:String,action:String,snooze:Boolean=false){writableDatabase.execSQL("INSERT INTO notification_state(task_id,last_fired_utc,last_action,snooze_count) VALUES(?,?,?,?) ON CONFLICT(task_id) DO UPDATE SET last_fired_utc=excluded.last_fired_utc,last_action=excluded.last_action,snooze_count=notification_state.snooze_count+excluded.snooze_count",arrayOf(taskId,System.currentTimeMillis()/1000,action,if(snooze)1 else 0))}
 @Synchronized fun cursor()=readableDatabase.rawQuery("SELECT server_cursor FROM runtime WHERE singleton=1",null).use{it.moveToFirst();it.getLong(0)}
 @Synchronized fun cursor(v:Long){writableDatabase.execSQL("UPDATE runtime SET server_cursor=?,last_sync_utc=? WHERE singleton=1",arrayOf(v,System.currentTimeMillis()/1000))}
 @Synchronized fun saveReward(key:String,event:String,type:String,eid:String,xp:Int,coins:Int,utc:Long){if(rows("reward").mapNotNull{Codec.reward(it.id,it.payload)}.any{it.sourceKey==key})return;val w=RewardModel("rw_"+UUID.randomUUID().toString().replace("-",""),key,event,type,eid,xp,coins,utc);save("reward",w.id,Codec.reward(w))}
}
