package com.planjoy.r7
import android.content.Context
import android.net.Uri
import org.json.*
import java.net.*
object SyncEngine{
 data class R(val ok:Boolean,val msg:String,val up:Int=0,val down:Int=0)
 private fun p(c:Context)=c.getSharedPreferences("r7_sync",Context.MODE_PRIVATE)
 fun endpoint(c:Context)=p(c).getString("endpoint","")?:""
 fun account(c:Context)=p(c).getString("account","")?:""
 fun configured(c:Context)=endpoint(c).isNotBlank()&&account(c).isNotBlank()&&!CryptoVault(c).secret("token").isNullOrBlank()
 fun recovery(c:Context)=CryptoVault(c).recoveryText();fun keyId(c:Context)=CryptoVault(c).keyId()
 fun devices(c:Context):List<R72Device>{val raw=p(c).getString("devices","[]")?:"[]";return try{val a=JSONArray(raw);(0 until a.length()).map{val j=a.getJSONObject(it);R72Device(j.optString("id"),j.optString("name"),j.optString("platform"),j.optString("app_version"),j.optLong("last_seen_utc",j.optLong("last_seen")),j.optBoolean("revoked"))}}catch(_:Exception){emptyList()}}
 fun safe(s:String)=try{val u=Uri.parse(s);u.scheme=="https"||(u.scheme=="http"&&(u.host=="127.0.0.1"||u.host=="localhost"))}catch(_:Exception){false}
 fun configure(c:Context,ep:String,acct:String,tok:String,rec:String){require(safe(ep));val v=CryptoVault(c);v.importRecovery(rec);v.secret("token",tok);p(c).edit().putString("endpoint",ep.trimEnd('/')).putString("account",acct).apply()}
 fun create(c:Context,ep:String):R=try{require(safe(ep));val v=CryptoVault(c);val x=post(ep.trimEnd('/')+"/v2/accounts",null,JSONObject().put("key_id",v.keyId()).toString());if(x.first !in 200..299)R(false,"HTTP ${x.first}")else{val j=JSONObject(x.second);v.secret("token",j.getString("token"));p(c).edit().putString("endpoint",ep.trimEnd('/')).putString("account",j.getString("account_id")).apply();R(true,j.getString("account_id"))}}catch(e:Exception){R(false,e.message?:"create failed")}
 fun sync(c:Context):R{
  if(!configured(c))return R(false,"Not configured");val db=PlanJoyDb.get(c);val v=CryptoVault(c);val ep=endpoint(c);val ac=account(c);val tk=v.secret("token")?:return R(false,"Missing token");var up=0;var dn=0
  return try{repeat(20){val a=JSONArray();db.pending().forEach{o->a.put(JSONObject().put("op_id",o.opId).put("device_id",o.deviceId).put("entity_type",o.type).put("entity_id",o.entityId).put("kind",o.kind).put("revision",o.revision).put("hlc_utc",o.hlcUtc).put("hlc_counter",o.hlcCounter).put("payload",v.encrypt(ac,o,o.payload)))};val dev=JSONObject().put("id",db.deviceId()).put("name",android.os.Build.MODEL).put("platform","android").put("app_version","0.7.3");val q=JSONObject().put("account_id",ac).put("key_id",v.keyId()).put("device",dev).put("cursor",db.cursor()).put("ops",a);val x=post("$ep/v2/sync",tk,q.toString());if(x.first !in 200..299)return R(false,"HTTP ${x.first}: ${x.second}",up,dn);val j=JSONObject(x.second);val aa=j.optJSONArray("accepted")?:JSONArray();val ids=(0 until aa.length()).map{aa.getString(it)};db.ack(ids);up+=ids.size;val oo=j.optJSONArray("ops")?:JSONArray();for(i in 0 until oo.length()){val z=oo.getJSONObject(i);val o=SyncOp(z.optLong("seq"),z.getString("op_id"),z.getString("device_id"),z.getString("entity_type"),z.getString("entity_id"),z.getInt("kind"),z.getLong("revision"),z.getLong("hlc_utc"),z.getLong("hlc_counter"),z.optString("payload",""));db.apply(o,v.decrypt(ac,o,o.payload));dn++};j.optJSONArray("devices")?.let{p(c).edit().putString("devices",it.toString()).apply()};db.cursor(j.getLong("cursor"));db.setSetting("last_sync_utc",(System.currentTimeMillis()/1000).toString());if(!j.optBoolean("has_more")&&db.pending().isEmpty()){R72WidgetUpdater.refreshAll(c);return R(true,"Synced",up,dn)}};R(false,"Page limit",up,dn)}catch(e:Exception){R(false,e.message?:"sync failed",up,dn)}
 }
 fun revoke(c:Context,deviceId:String):R{if(!configured(c))return R(false,"Not configured");return try{val tk=CryptoVault(c).secret("token")?:return R(false,"Missing token");val body=JSONObject().put("account_id",account(c)).put("device_id",deviceId).toString();val x=post(endpoint(c)+"/v2/devices/revoke",tk,body);if(x.first !in 200..299)R(false,"HTTP ${x.first}") else {val keep=devices(c).map{if(it.id==deviceId)it.copy(revoked=true) else it};val a=JSONArray();keep.forEach{a.put(JSONObject().put("id",it.id).put("name",it.name).put("platform",it.platform).put("app_version",it.appVersion).put("last_seen",it.lastSeenUtc).put("revoked",it.revoked))};p(c).edit().putString("devices",a.toString()).apply();R(true,"revoked")}}catch(e:Exception){R(false,e.message?:"revoke failed")}}
 private fun post(url:String,token:String?,body:String):Pair<Int,String>{val h=URL(url).openConnection() as HttpURLConnection;h.requestMethod="POST";h.connectTimeout=15000;h.readTimeout=30000;h.doOutput=true;h.setRequestProperty("Content-Type","application/json");token?.let{h.setRequestProperty("Authorization","Bearer $it")};h.outputStream.use{it.write(body.toByteArray())};val code=h.responseCode;val txt=(if(code in 200..299)h.inputStream else h.errorStream)?.bufferedReader()?.use{it.readText()}?:"";h.disconnect();return code to txt}
}
