app=replace_function(app,'renderWidgets',widget_func)
render_widget='''function renderWidget(){applyRoot();const type=widgetMode,cards=widgetCards(),row=cards.find(x=>x[0]===type)||cards[0],[k,h,v,n,meta]=row;let extra='';if(k==='quadrant'){const q=[1,2,3,4].map(x=>(state.tasks||[]).filter(t=>!t.completed&&(t.quadrant||2)===x).length);extra=`<div class="widget-mini-grid">${q.map((x,i)=>`<span>Q${i+1}: ${digits(x)}</span>`).join('')}</div>`}if(k==='week'){const days=[0,1,2,3,4,5,6].map(off=>{const d=new Date();d.setDate(d.getDate()+off);return (state.tasks||[]).filter(t=>!t.completed&&sameDateSec(t.startUtc,d)).length});extra=`<div class="widget-mini-grid">${days.map((x,i)=>`<span>+${i} · ${digits(x)}</span>`).join('')}</div>`}const privacy=state.settings.widgetPrivacy;$('#app').innerHTML=`<div class="widget-shell"><div class="widget-card widget-${esc(k)}"><div class="widget-drag"></div><button class="widget-close" data-widget-close>×</button><h3>PlanJoy · ${esc(h)}</h3><div class="widget-big">${esc(privacy?'•••':v)}</div><div class="widget-note">${esc(privacy?tr('Details hidden','جزئیات مخفی است'):n)}</div>${privacy?'':extra}<div class="widget-note">${esc(meta||'')}</div></div></div>`;$('[data-widget-close]')?.addEventListener('click',()=>window.close())}
'''
app=replace_function(app,'renderWidget',render_widget)

# bind settings
m="$$('[data-calendar]').forEach(b=>b.addEventListener('click',()=>{state.settings.calendar=b.dataset.calendar;persist()}));"
app=rep(app,m,m+"\n  $$('[data-widget-size]').forEach(b=>b.addEventListener('click',()=>{state.settings.widgetSize=b.dataset.widgetSize;persist()}));\n  $('[data-widget-opacity]')?.addEventListener('input',e=>{state.settings.widgetOpacity=Number(e.target.value);persist(false)});\n  $('[data-backup-hours]')?.addEventListener('change',e=>{state.settings.autoBackupHours=Number(e.target.value);persist()});\n  $('[data-ai-endpoint]')?.addEventListener('change',e=>{state.settings.aiEndpoint=e.target.value.trim();persist()});",'bind settings')

# settings content
app=app.replace('Keep this enabled for future scheduled snapshots. Manual backup is available now.','When enabled, PlanJoy writes rotating local snapshots automatically while it is running.').replace('برای Snapshotهای زمان‌بندی‌شده آینده روشن بماند؛ پشتیبان دستی همین حالا در دسترس است.','وقتی روشن باشد، PlanJoy هنگام اجرا Snapshotهای چرخشی محلی را به‌صورت خودکار می‌سازد.')
old="${switchHtml('autoBackup',s.autoBackup)}</div></div>`;"
new="${switchHtml('autoBackup',s.autoBackup)}</div><div class=\"setting-inline\" style=\"margin-top:10px\"><span class=\"setting-desc\">${tr('Backup interval','فاصله پشتیبان')}:</span><select class=\"select\" data-backup-hours>${[1,3,6,12,24,48].map(x=>`<option value=\"${x}\" ${Number(s.autoBackupHours||24)===x?'selected':''}>${digits(x)} ${tr('hours','ساعت')}</option>`).join('')}</select></div></div>`;"
app=rep(app,old,new,'backup hours')
ai_old="<div class=\"card setting-card\"><div class=\"setting-row\"><div class=\"grow\"><div class=\"setting-title\">${tr('Cloud AI consent','رضایت برای هوش ابری')}</div><div class=\"setting-desc\">${tr('Off by default. Local Smart Plan works without sending your text anywhere.','پیش‌فرض خاموش است؛ Smart Plan محلی بدون ارسال متن شما کار می‌کند.')}</div></div>${switchHtml('aiConsent',s.aiConsent)}</div></div>"
ai_new="<div class=\"card setting-card\"><div class=\"setting-row\"><div class=\"grow\"><div class=\"setting-title\">${tr('Optional cloud AI','هوش ابری اختیاری')}</div><div class=\"setting-desc\">${tr('Local Smart Plan always works. Cloud enhancement is used only when consent is on and an HTTPS endpoint is configured.','Smart Plan محلی همیشه کار می‌کند؛ ارتقای ابری فقط با رضایت روشن و آدرس HTTPS تنظیم‌شده استفاده می‌شود.')}</div></div>${switchHtml('aiConsent',s.aiConsent)}</div><div class=\"field\" style=\"margin-top:10px\"><label>${tr('AI endpoint','آدرس AI')}</label><input class=\"input\" data-ai-endpoint value=\"${esc(s.aiEndpoint||'')}\" placeholder=\"https://…\"></div></div>"
app=rep(app,ai_old,ai_new,'ai settings')
app=app.replace('English uses Segoe UI. Persian switches immediately to the native Windows font stack and full RTL.','English uses Segoe UI. Persian switches immediately to the embedded IRANSansXV variable font and full RTL.').replace('انگلیسی از Segoe UI استفاده می‌کند؛ فارسی بلافاصله از قلم‌های استاندارد ویندوز و راست‌به‌چپ کامل تغییر می‌کند.','انگلیسی از Segoe UI استفاده می‌کند؛ فارسی بلافاصله با فونت IRANSansXV داخلی و راست‌به‌چپ کامل نمایش داده می‌شود.')

# optional cloud AI UI/handler
app=app.replace("<button class=\"btn primary\" style=\"margin-top:12px\" data-action=\"smart-create\">✧ ${tr('Create this plan','ساخت این برنامه')}</button>","<div style=\"display:flex;gap:8px;margin-top:12px;flex-wrap:wrap\"><button class=\"btn primary\" data-action=\"smart-create\">✧ ${tr('Create this plan','ساخت این برنامه')}</button>${state.settings.aiConsent&&state.settings.aiEndpoint?`<button class=\"btn soft\" data-action=\"smart-enhance\">☁ ${tr('Enhance with cloud AI','ارتقا با AI ابری')}</button>`:''}</div>")
app=rep(app,"  if(a==='smart-create'){if(!smartText.trim())return toast(tr('Write a plan first.','اول برنامه را بنویس.'),'error');quickAdd(smartText);route='today';plannerView='today';smartText='';shell()}","  if(a==='smart-enhance'){if(!smartText.trim())return toast(tr('Write a plan first.','اول برنامه را بنویس.'),'error');try{const r=await window.planjoy.smartEnhance({text:smartText});const d=r?.data||{};if(d.text)smartText=String(d.text);else if(d.title)smartText=String(d.title);renderPage();bindPage();toast(tr('Cloud enhancement applied.','پیشنهاد ابری اعمال شد.'),'success')}catch(err){toast(err.message||tr('Cloud AI failed.','AI ابری ناموفق بود.'),'error')}}\n  if(a==='smart-create'){if(!smartText.trim())return toast(tr('Write a plan first.','اول برنامه را بنویس.'),'error');quickAdd(smartText);route='today';plannerView='today';smartText='';shell()}",'smart AI handler')

# main widgets
main=rep(main,"  const allowed=['today','focus','goal','countdown']; if(!allowed.includes(type))return false;\n  const old=widgets.get(type);if(old&&!old.isDestroyed()){old.show();old.focus();return true;}\n  const w=new BrowserWindow({width:370,height:210,minWidth:300,minHeight:150,alwaysOnTop:true,frame:false,transparent:false,resizable:true,skipTaskbar:false,backgroundColor:'#FAFAFA',webPreferences:{preload:path.join(__dirname,'preload.js'),contextIsolation:true,nodeIntegration:false,sandbox:true,backgroundThrottling:false}});","  const allowed=['today','focus','goal','countdown','calendar','week','quadrant','mood','stats','joy']; if(!allowed.includes(type))return false;\n  const old=widgets.get(type);if(old&&!old.isDestroyed()){old.show();old.focus();return true;}\n  const s=normalizeState(readStateRaw()||defaultState()),size=s.settings.widgetSize||'medium';const dims=size==='small'?{width:320,height:180}:size==='wide'?{width:520,height:220}:{width:390,height:220};\n  const w=new BrowserWindow({...dims,minWidth:290,minHeight:150,alwaysOnTop:true,frame:false,transparent:false,resizable:true,skipTaskbar:false,backgroundColor:'#FAFAFA',webPreferences:{preload:path.join(__dirname,'preload.js'),contextIsolation:true,nodeIntegration:false,sandbox:true,backgroundThrottling:false}});",'widget allowlist')

# auto backup & reminders
idx=main.index('function runScheduler(){')
main=main[:idx]+"function rotateAutoBackups(state){if(!state.settings.autoBackup)return false;const hours=Math.max(1,Number(state.settings.autoBackupHours||24)),last=Number(state.diagnostics?.lastAutoBackupUtc||0),now=epoch();if(last&&now-last<hours*3600)return false;const dir=path.join(dataDir,'backups');fs.mkdirSync(dir,{recursive:true});const stamp=new Date().toISOString().replaceAll(':','-').replaceAll('.','-');const out=path.join(dir,`PlanJoy-auto-${stamp}.json`);fs.writeFileSync(out,JSON.stringify(state,null,2));state.diagnostics=state.diagnostics||{};state.diagnostics.lastAutoBackupUtc=now;state.diagnostics.lastAutoBackupPath=out;const files=fs.readdirSync(dir).filter(x=>/^PlanJoy-auto-.*\\.json$/.test(x)).map(x=>({p:path.join(dir,x),m:fs.statSync(path.join(dir,x)).mtimeMs})).sort((a,b)=>b.m-a.m);for(const f of files.slice(12))try{fs.unlinkSync(f.p)}catch{}audit('auto_backup',out);return true}\n"+main[idx:]
main=rep(main,"    const now=epoch(); let changed=false;\n    for(const t of s.tasks.filter(x=>!x.completed)){\n      const lead=Math.max(-1,Number(t.reminderLead??-1)); if(lead<0)continue;\n      const fireAt=(Number(t.startUtc)||0)-lead*60; if(fireAt<=0||fireAt>now||now-fireAt>180)continue;\n      const key=`${t.id}:${fireAt}`; if(s.notificationLog.some(x=>x.key===key))continue;\n      if(Notification.isSupported()) new Notification({title:'PlanJoy',body:t.title,silent:!s.settings.sounds}).show();\n      s.notificationLog.push({key,taskId:t.id,utc:now,action:'fired'});changed=true;\n    }\n    if(changed){s.notificationLog=s.notificationLog.slice(-500);writeStateRaw(s);broadcast(s);}","    const now=epoch(); let changed=rotateAutoBackups(s);\n    for(const t of s.tasks.filter(x=>!x.completed)){\n      const lead=Math.max(-1,Number(t.reminderLead??-1)); if(lead<0)continue;\n      const fireAt=(Number(t.startUtc)||0)-lead*60; if(fireAt<=0||fireAt>now)continue;\n      const continuous=!!s.settings.continuousReminders&&!!t.continuousReminder,windowEnd=Math.max(Number(t.endUtc||0),Number(t.startUtc||0)+7200);if(!continuous&&now-fireAt>180)continue;if(continuous&&now>windowEnd)continue;\n      const bucket=continuous?Math.floor((now-fireAt)/300):0,key=`${t.id}:${fireAt}:${bucket}`; if(s.notificationLog.some(x=>x.key===key))continue;\n      if(Notification.isSupported()) new Notification({title:'PlanJoy',body:t.title,silent:!s.settings.sounds}).show();\n      s.notificationLog.push({key,taskId:t.id,utc:now,action:continuous?'continuous':'fired'});changed=true;\n    }\n    if(changed){s.notificationLog=s.notificationLog.slice(-800);writeStateRaw(s);broadcast(s);}",'scheduler')

# AI IPC/preload
m="  ipcMain.handle('widget:open',(_,t)=>openWidget(String(t)));"
main=rep(main,m,m+"\n  ipcMain.handle('ai:enhance',async(_,payload)=>{const s=normalizeState(readStateRaw());if(!s.settings.aiConsent)throw new Error('Cloud AI consent is off');const endpoint=String(s.settings.aiEndpoint||'').trim(),u=new URL(endpoint);if(u.protocol!=='https:')throw new Error('AI endpoint must use HTTPS');const ctrl=new AbortController(),timer=setTimeout(()=>ctrl.abort(),12000);try{const r=await fetch(u,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({text:String(payload?.text||''),locale:s.settings.language,calendar:s.settings.calendar}),signal:ctrl.signal});if(!r.ok)throw new Error(`AI endpoint HTTP ${r.status}`);return {ok:true,data:await r.json()}}finally{clearTimeout(timer)}});",'ai ipc')
pre=rep(pre,"  openWidget: type => invoke('widget:open', String(type || 'today')),","  openWidget: type => invoke('widget:open', String(type || 'today')),\n  smartEnhance: payload => invoke('ai:enhance', payload || {}),",'preload ai')

# contract: accept embedded font and new version
font_hash=hashlib.sha256((root/'assets/fonts/IRANSansXVF.ttf').read_bytes()).hexdigest()
test=test.replace("pkg.version==='0.7.4'","pkg.version==='0.7.5'")
test=test.replace("'native Windows font stack'","'IRANSansXV'").replace("ok(css.includes('font-family:Tahoma,\"Segoe UI\",sans-serif'),'system font stack');","ok(css.includes(\"font-family:'IRANSansXV'\"),'IRANSans font stack');")
test=test.replace("ok(!fs.existsSync(path.join(root,'assets/fonts/IRANSansXVF.ttf')),'no private font redistributed');",f"const font=fs.readFileSync(path.join(root,'assets/fonts/IRANSansXVF.ttf'));ok(require('crypto').createHash('sha256').update(font).digest('hex')==='{font_hash}','exact user IRANSansXVF');")
test=test.replace("console.log(`DESKTOP_CONTRACT_PASS ${pass}`);","")
test += "\nok(main.includes(\"['today','focus','goal','countdown','calendar','week','quadrant','mood','stats','joy']\"),'ten widgets');ok(main.includes('rotateAutoBackups'),'automatic backup');ok(main.includes(\"continuous?'continuous':'fired'\"),'continuous reminders');ok(main.includes(\"'ai:enhance'\"),'cloud AI IPC');ok(app.includes('ensureNextOccurrence'),'functional recurrence');ok(app.includes('data-widget-size'),'widget sizes');ok(app.includes('data-widget-opacity'),'widget opacity');ok(css.includes('.compact-mode .page'),'compact mode functional');\nconsole.log(`DESKTOP_CONTRACT_PASS ${pass}`);\n"

# functional certification hook in main process
cert_anchor='async function certifyUiRoutes()'
pos=main.find(cert_anchor)
if pos<0: raise RuntimeError('UI certification hook missing')
# Insert immediately before certifyUiRoutes only when not already present.
if 'FUNCTIONAL_PARITY_PASS settings recurrence backup widgets font' not in main:
    cert='''async function certifyFunctionalFlows(){
  if(process.env.PLANJOY_FUNCTION_CERTIFY!=='1')return;
  const wait=ms=>new Promise(r=>setTimeout(r,ms));
  const exec=code=>mainWindow.webContents.executeJavaScript(code,true);
  await wait(800);
  let st=normalizeState(readStateRaw()||defaultState());const original=JSON.parse(JSON.stringify(st));
  try{
    await exec(`document.querySelector('[data-route="settings"]').click();await new Promise(r=>setTimeout(r,120));const compact=document.querySelector('[data-setting-switch="compactMode"]');if(!compact)throw new Error('compact switch missing');compact.click();await new Promise(r=>setTimeout(r,160));return document.body.classList.contains('compact-mode')`).then(v=>{if(!v)throw new Error('compact mode visual class failed')});
    await exec(`document.querySelector('[data-lang="fa"]')?.click();await new Promise(r=>setTimeout(r,180));return {dir:document.documentElement.dir,font:getComputedStyle(document.body).fontFamily}`).then(v=>{if(v.dir!=='rtl'||!String(v.font).includes('IRANSansXV'))throw new Error('Persian IRANSans/RTL failed')});
    await exec(`document.querySelector('[data-calendar="jalali"]')?.click();await new Promise(r=>setTimeout(r,120));return true`);
    st=normalizeState(readStateRaw()||defaultState());if(st.settings.language!=='fa'||st.settings.calendar!=='jalali'||!st.settings.compactMode)throw new Error('settings did not persist');
    const base=epoch()+3600,tid='cert_repeat_'+Date.now();st.tasks.push({id:tid,title:'Certification recurrence',note:'',category:'Inbox',startUtc:base,endUtc:base+1800,allDay:false,priority:2,quadrant:2,completed:false,completedUtc:0,planned:true,deadlineUtc:base+1800,calendarSystem:0,sourceY:0,sourceM:0,sourceD:0,parentId:'',recurrenceId:tid,recurrenceCalendar:0,recurrenceFrequency:1,recurrenceInterval:1,anchorDay:0,anchorMonth:0,recurrenceUntil:0,occurrenceLimit:0,reminderLead:-1,repeat:'daily',continuousReminder:false,occurrenceIndex:0,sortOrder:99999});writeStateRaw(st);broadcast(st);await wait(200);
    await exec(`document.querySelector('[data-route="today"]').click();await new Promise(r=>setTimeout(r,150));const row=[...document.querySelectorAll('[data-task-row]')].find(x=>x.dataset.taskRow==='${tid}');if(!row)throw new Error('cert recurrence row missing');row.querySelector('[data-action="toggle-task"]').click();await new Promise(r=>setTimeout(r,220));return true`);
    st=normalizeState(readStateRaw()||defaultState());if(!st.tasks.some(x=>x.id!==tid&&(x.recurrenceId||x.id)===tid&&!x.completed))throw new Error('next recurrence not created');
    st.settings.autoBackup=true;st.settings.autoBackupHours=1;st.diagnostics.lastAutoBackupUtc=0;writeStateRaw(st);if(!rotateAutoBackups(st))throw new Error('auto backup did not execute');writeStateRaw(st);if(!st.diagnostics.lastAutoBackupPath||!fs.existsSync(st.diagnostics.lastAutoBackupPath))throw new Error('auto backup file missing');
    await exec(`document.querySelector('[data-route="widgets"]').click();await new Promise(r=>setTimeout(r,150));return document.querySelectorAll('[data-action="open-widget"]').length`).then(v=>{if(v<10)throw new Error('widget gallery incomplete: '+v)});
    const widgetTypes=['today','focus','goal','countdown','calendar','week','quadrant','mood','stats','joy'];
    for(const type of widgetTypes){if(!openWidget(type))throw new Error('widget open rejected: '+type);const w=widgets.get(type);await new Promise((resolve,reject)=>{if(!w||w.isDestroyed())return reject(new Error('widget missing '+type));if(!w.webContents.isLoading())return resolve();w.webContents.once('did-finish-load',resolve);setTimeout(()=>reject(new Error('widget timeout '+type)),5000)});const ok=await w.webContents.executeJavaScript(`!!document.querySelector('.widget-card.widget-${type}')`);if(!ok)throw new Error('widget render failed '+type);w.close();widgets.delete(type)}
    console.log('FUNCTIONAL_PARITY_PASS settings recurrence backup widgets font');
  }finally{writeStateRaw(original);broadcast(original)}
